### ISSUE TITLE
ChunkLoadError when service prod resources

### ISSUE THREAD

**Issue by obfu5c8** [ScriptedAlchemy/webpack-external-import#109]
After stumbling across this plugin via your MicroFrontEnd Architecture article i've been playing around with it for my build and had it working very successfully while both apps were running inside webpack-dev-server. 

Its a very simple setup, App (_A_) dynamically loads a single react component from App (_B_).

I then did a full prod build (_B_) and served the dist folder locally with the npm `serve` package. 
After switching the import url in (_A_) to point at (_B_)'s dist server, the import started throwing a ChunkLoadError at `bootstrap:259` (inside the onScriptComplete function).

I can see in the network logs that both the importManifest.js and the chunk file itself have been loaded into the browser successfully, so I'm totally lost as to why there's a behaviour change.

Any suggestions on what to poke next?

**Comment by ScriptedAlchemy** [comment]
Try loading only one component at a time. I’m working out race conditions in tree shaken envs - got it working today, just need to repack it into the plugin. If you reload the page. Does it show up?

**Comment by ScriptedAlchemy** [comment]
So what’s going on is that when your chunk needs more dependencies, it recursively Calls require.interleave, however how it watches for code to be installed is a little different than what I need for nested deps. So everything ends up resolving before the chunk totally done installing. 

When running multiple interleaved files at one in parallel. They all write to the same queue. The recursive function doesn’t handle child calls correctly when there’s multiple and duplicates. In prod mode. Mostly because of scope changes and optimization.

**Comment by ScriptedAlchemy** [comment]
So the working solution I have is to loop and return an array of promises for each nested chain. Then wait for those to resolve and be installed by webpack before resolving the parents and checking they are installed.

**Comment by ScriptedAlchemy** [comment]
The file gets there but webpack is still registering the chunk modules. It resolves a little too soon

**Comment by ScriptedAlchemy** [comment]
@obfu5c8 this fixes it https://github.com/ScriptedAlchemy/webpack-external-import/pull/111

Working on some cleanup and will release in a few days.  Need to validate the rewrite still handles errors as expected
